using System.Collections.Generic;
using UnityEngine;

namespace DrifterBossGrabMod.Config
{
    // Hardcoded preset definitions for DrifterBossGrabMod.
    public static class PresetDefinitions
    {
        public static readonly Dictionary<PresetType, Dictionary<string, object>> Presets = new()
        {
            // Vanilla: All features disabled, vanilla behavior
            [PresetType.Vanilla] = new Dictionary<string, object>
            {
                // General settings
                ["General.EnableBossGrabbing"] = false,
                ["General.EnableNPCGrabbing"] = false,
                ["General.EnableEnvironmentGrabbing"] = false,
                ["General.EnableLockedObjectGrabbing"] = false,
                ["General.ProjectileGrabbingMode"] = ProjectileGrabbingMode.None,
                ["General.EnableDebugLogs"] = false,
                ["General.EnableConfigSync"] = true,

                // Persistence settings
                ["Persistence.EnableObjectPersistence"] = false,
                ["Persistence.EnableAutoGrab"] = false,
                ["Persistence.PersistBaggedBosses"] = true,
                ["Persistence.PersistBaggedNPCs"] = true,
                ["Persistence.PersistBaggedEnvironmentObjects"] = true,
                ["Persistence.AutoGrabDelay"] = 1.0f,

                // Bottomless Bag settings
                ["BottomlessBag.EnableBottomlessBag"] = false,
                ["BottomlessBag.AddedCapacity"] = "0",
                ["BottomlessBag.EnableStockRefreshClamping"] = false,
                ["BottomlessBag.CycleCooldown"] = 0.2f,
                ["BottomlessBag.EnableMouseWheelScrolling"] = true,
                ["BottomlessBag.InverseMouseWheelScrolling"] = false,
                ["BottomlessBag.AutoPromoteMainSeat"] = true,
                ["BottomlessBag.PrioritizeMainSeat"] = false,

                // HUD settings
                ["Hud.EnableCarouselHUD"] = false,
                ["Hud.CarouselSpacing"] = 45.0f,
                ["Hud.CarouselAnimationDuration"] = 0.4f,
                ["Hud.CenterSlotX"] = 25.0f,
                ["Hud.CenterSlotY"] = 50.0f,
                ["Hud.CenterSlotScale"] = 1.0f,
                ["Hud.CenterSlotOpacity"] = 1.0f,
                ["Hud.CenterSlotShowIcon"] = true,
                ["Hud.CenterSlotShowWeightIcon"] = true,
                ["Hud.CenterSlotShowName"] = true,
                ["Hud.CenterSlotShowHealthBar"] = true,
                ["Hud.CenterSlotShowSlotNumber"] = true,
                ["Hud.SideSlotX"] = 20.0f,
                ["Hud.SideSlotY"] = 5.0f,
                ["Hud.SideSlotScale"] = 0.8f,
                ["Hud.SideSlotOpacity"] = 0.3f,
                ["Hud.SideSlotShowIcon"] = true,
                ["Hud.SideSlotShowWeightIcon"] = true,
                ["Hud.SideSlotShowName"] = true,
                ["Hud.SideSlotShowHealthBar"] = true,
                ["Hud.SideSlotShowSlotNumber"] = true,
                ["Hud.EnableDamagePreview"] = false,
                ["Hud.DamagePreviewColor"] = new Color(1f, 0.15f, 0.15f, 0.8f),
                ["Hud.UseNewWeightIcon"] = false,
                ["Hud.WeightDisplayMode"] = WeightDisplayMode.Multiplier,
                ["Hud.ScaleWeightColor"] = true,
                ["Hud.ShowTotalMassOnWeightIcon"] = false,
                ["Hud.EnableMassCapacityUI"] = false,
                ["Hud.MassCapacityUIPositionX"] = -20.0f,
                ["Hud.MassCapacityUIPositionY"] = 0.0f,
                ["Hud.MassCapacityUIScale"] = 0.8f,
                ["Hud.EnableSeparators"] = true,
                ["Hud.GradientIntensity"] = 1.0f,

                // Balance settings
                ["Balance.EnableBalance"] = false,
                ["Balance.BreakoutTimeMultiplier"] = 1.0f,
                ["Balance.MaxSmacks"] = 3,
                ["Balance.AoEDamageDistribution"] = AoEDamageMode.None,
                ["Balance.SlotScalingFormula"] = "0",
                ["Balance.MassCapacityFormula"] = "S * 100",
                ["Balance.EliteFlagMultiplier"] = "1",
                ["Balance.BossFlagMultiplier"] = "1",
                ["Balance.ChampionFlagMultiplier"] = "1",
                ["Balance.PlayerFlagMultiplier"] = "1",
                ["Balance.MinionFlagMultiplier"] = "1",
                ["Balance.DroneFlagMultiplier"] = "1",
                ["Balance.MechanicalFlagMultiplier"] = "1",
                ["Balance.VoidFlagMultiplier"] = "1",
                ["Balance.AllFlagMultiplier"] = "1",
                ["Balance.OverencumbranceMax"] = 100.0f,
                ["Balance.StateCalculationMode"] = StateCalculationMode.Current,

                ["Balance.MovespeedPenaltyFormula"] = "0",
                ["Balance.BagScaleCap"] = "1",
                ["Balance.MassCap"] = "700",
            },
            
            // Intended: Boss grab only
            [PresetType.Intended] = new Dictionary<string, object>
            {
                // General settings
                ["General.EnableBossGrabbing"] = true,
                ["General.EnableNPCGrabbing"] = false,
                ["General.EnableEnvironmentGrabbing"] = false,
                ["General.EnableLockedObjectGrabbing"] = false,
                ["General.ProjectileGrabbingMode"] = ProjectileGrabbingMode.None,
                ["General.EnableDebugLogs"] = false,
                ["General.EnableConfigSync"] = true,
                
                // Persistence settings
                ["Persistence.EnableObjectPersistence"] = false,
                ["Persistence.EnableAutoGrab"] = false,
                ["Persistence.PersistBaggedBosses"] = true,
                ["Persistence.PersistBaggedNPCs"] = true,
                ["Persistence.PersistBaggedEnvironmentObjects"] = true,
                ["Persistence.AutoGrabDelay"] = 1.0f,
                
                // Bottomless Bag settings
                ["BottomlessBag.EnableBottomlessBag"] = false,
                ["BottomlessBag.AddedCapacity"] = "0",
                ["BottomlessBag.EnableStockRefreshClamping"] = false,
                ["BottomlessBag.CycleCooldown"] = 0.2f,
                ["BottomlessBag.EnableMouseWheelScrolling"] = true,
                ["BottomlessBag.InverseMouseWheelScrolling"] = false,
                ["BottomlessBag.AutoPromoteMainSeat"] = true,
                ["BottomlessBag.PrioritizeMainSeat"] = false,
                
                // HUD settings
                ["Hud.EnableCarouselHUD"] = false,
                ["Hud.CarouselSpacing"] = 45.0f,
                ["Hud.CarouselAnimationDuration"] = 0.4f,
                ["Hud.CenterSlotX"] = 25.0f,
                ["Hud.CenterSlotY"] = 50.0f,
                ["Hud.CenterSlotScale"] = 1.0f,
                ["Hud.CenterSlotOpacity"] = 1.0f,
                ["Hud.CenterSlotShowIcon"] = true,
                ["Hud.CenterSlotShowWeightIcon"] = true,
                ["Hud.CenterSlotShowName"] = true,
                ["Hud.CenterSlotShowHealthBar"] = true,
                ["Hud.CenterSlotShowSlotNumber"] = true,
                ["Hud.SideSlotX"] = 20.0f,
                ["Hud.SideSlotY"] = 5.0f,
                ["Hud.SideSlotScale"] = 0.8f,
                ["Hud.SideSlotOpacity"] = 0.3f,
                ["Hud.SideSlotShowIcon"] = true,
                ["Hud.SideSlotShowWeightIcon"] = true,
                ["Hud.SideSlotShowName"] = true,
                ["Hud.SideSlotShowHealthBar"] = true,
                ["Hud.SideSlotShowSlotNumber"] = true,
                ["Hud.EnableDamagePreview"] = true,
                ["Hud.DamagePreviewColor"] = new Color(1f, 0.15f, 0.15f, 0.8f),
                ["Hud.UseNewWeightIcon"] = false,
                ["Hud.WeightDisplayMode"] = WeightDisplayMode.Multiplier,
                ["Hud.ScaleWeightColor"] = true,
                ["Hud.EnableMassCapacityUI"] = true,
                ["Hud.MassCapacityUIPositionX"] = -20.0f,
                ["Hud.MassCapacityUIPositionY"] = 0.0f,
                ["Hud.MassCapacityUIScale"] = 0.8f,
                ["Hud.EnableSeparators"] = true,
                ["Hud.GradientIntensity"] = 1.0f,
                
                // Balance settings
                ["Balance.EnableBalance"] = false,
                ["Balance.BreakoutTimeMultiplier"] = 1.0f,
                ["Balance.MaxSmacks"] = 3,
                ["Balance.AoEDamageDistribution"] = AoEDamageMode.None,
                ["Balance.SlotScalingFormula"] = "0",
                ["Balance.MassCapacityFormula"] = "S * 100",
                ["Balance.EliteFlagMultiplier"] = "1",
                ["Balance.BossFlagMultiplier"] = "1",
                ["Balance.ChampionFlagMultiplier"] = "1",
                ["Balance.PlayerFlagMultiplier"] = "1",
                ["Balance.MinionFlagMultiplier"] = "1",
                ["Balance.DroneFlagMultiplier"] = "1",
                ["Balance.MechanicalFlagMultiplier"] = "1",
                ["Balance.VoidFlagMultiplier"] = "1",
                ["Balance.AllFlagMultiplier"] = "1",
                ["Balance.OverencumbranceMax"] = 100.0f,
                ["Balance.StateCalculationMode"] = StateCalculationMode.Current,

                ["Balance.MovespeedPenaltyFormula"] = "0",
                ["Balance.BagScaleCap"] = "1",
                ["Balance.MassCap"] = "700",
            },
            
            // Default: All features in DrifterGrabFeature + bottomless bag and persistence
            [PresetType.Default] = new Dictionary<string, object>
            {
                // General settings
                ["General.EnableBossGrabbing"] = true,
                ["General.EnableNPCGrabbing"] = true,
                ["General.EnableEnvironmentGrabbing"] = true,
                ["General.EnableLockedObjectGrabbing"] = true,
                ["General.ProjectileGrabbingMode"] = ProjectileGrabbingMode.SurvivorOnly,
                ["General.EnableDebugLogs"] = false,
                ["General.EnableConfigSync"] = true,
                
                // Persistence settings
                ["Persistence.EnableObjectPersistence"] = true,
                ["Persistence.EnableAutoGrab"] = true,
                ["Persistence.PersistBaggedBosses"] = true,
                ["Persistence.PersistBaggedNPCs"] = true,
                ["Persistence.PersistBaggedEnvironmentObjects"] = true,
                ["Persistence.AutoGrabDelay"] = 1.0f,
                
                // Bottomless Bag settings
                ["BottomlessBag.EnableBottomlessBag"] = true,
                ["BottomlessBag.AddedCapacity"] = "2",
                ["BottomlessBag.EnableStockRefreshClamping"] = true,
                ["BottomlessBag.CycleCooldown"] = 0.2f,
                ["BottomlessBag.EnableMouseWheelScrolling"] = true,
                ["BottomlessBag.InverseMouseWheelScrolling"] = false,
                ["BottomlessBag.AutoPromoteMainSeat"] = true,
                ["BottomlessBag.PrioritizeMainSeat"] = false,
                
                // HUD settings
                ["Hud.EnableCarouselHUD"] = true,
                ["Hud.CarouselSpacing"] = 45.0f,
                ["Hud.CarouselAnimationDuration"] = 0.4f,
                ["Hud.CenterSlotX"] = 25.0f,
                ["Hud.CenterSlotY"] = 50.0f,
                ["Hud.CenterSlotScale"] = 1.0f,
                ["Hud.CenterSlotOpacity"] = 1.0f,
                ["Hud.CenterSlotShowIcon"] = true,
                ["Hud.CenterSlotShowWeightIcon"] = true,
                ["Hud.CenterSlotShowName"] = true,
                ["Hud.CenterSlotShowHealthBar"] = true,
                ["Hud.CenterSlotShowSlotNumber"] = true,
                ["Hud.SideSlotX"] = 20.0f,
                ["Hud.SideSlotY"] = 5.0f,
                ["Hud.SideSlotScale"] = 0.8f,
                ["Hud.SideSlotOpacity"] = 0.3f,
                ["Hud.SideSlotShowIcon"] = true,
                ["Hud.SideSlotShowWeightIcon"] = true,
                ["Hud.SideSlotShowName"] = true,
                ["Hud.SideSlotShowHealthBar"] = true,
                ["Hud.SideSlotShowSlotNumber"] = true,
                ["Hud.EnableDamagePreview"] = true,
                ["Hud.DamagePreviewColor"] = new Color(1f, 0.15f, 0.15f, 0.8f),
                ["Hud.UseNewWeightIcon"] = false,
                ["Hud.WeightDisplayMode"] = WeightDisplayMode.Multiplier,
                ["Hud.ScaleWeightColor"] = true,
                ["Hud.EnableMassCapacityUI"] = true,
                ["Hud.MassCapacityUIPositionX"] = -20.0f,
                ["Hud.MassCapacityUIPositionY"] = 0.0f,
                ["Hud.MassCapacityUIScale"] = 0.8f,
                ["Hud.EnableSeparators"] = true,
                ["Hud.GradientIntensity"] = 1.0f,
                
                // Balance settings
                ["Balance.EnableBalance"] = false,
                ["Balance.BreakoutTimeMultiplier"] = 1.0f,
                ["Balance.MaxSmacks"] = 3,
                ["Balance.AoEDamageDistribution"] = AoEDamageMode.None,
                ["Balance.SlotScalingFormula"] = "0",
                ["Balance.MassCapacityFormula"] = "0",
                ["Balance.EliteFlagMultiplier"] = "1",
                ["Balance.BossFlagMultiplier"] = "1",
                ["Balance.ChampionFlagMultiplier"] = "1",
                ["Balance.PlayerFlagMultiplier"] = "1",
                ["Balance.MinionFlagMultiplier"] = "1",
                ["Balance.DroneFlagMultiplier"] = "1",
                ["Balance.MechanicalFlagMultiplier"] = "1",
                ["Balance.VoidFlagMultiplier"] = "1",
                ["Balance.AllFlagMultiplier"] = "1",
                ["Balance.OverencumbranceMax"] = 100.0f,
                ["Balance.StateCalculationMode"] = StateCalculationMode.Current,

                ["Balance.MovespeedPenaltyFormula"] = "0",
                ["Balance.BagScaleCap"] = "1",
                ["Balance.MassCap"] = "700",
            },
            
            // Balance: Default + balance features
            [PresetType.Balance] = new Dictionary<string, object>
            {
                // General settings
                ["General.EnableBossGrabbing"] = true,
                ["General.EnableNPCGrabbing"] = true,
                ["General.EnableEnvironmentGrabbing"] = true,
                ["General.EnableLockedObjectGrabbing"] = true,
                ["General.ProjectileGrabbingMode"] = ProjectileGrabbingMode.SurvivorOnly,
                ["General.EnableDebugLogs"] = false,
                ["General.EnableConfigSync"] = true,
                
                // Persistence settings
                ["Persistence.EnableObjectPersistence"] = true,
                ["Persistence.EnableAutoGrab"] = true,
                ["Persistence.PersistBaggedBosses"] = true,
                ["Persistence.PersistBaggedNPCs"] = true,
                ["Persistence.PersistBaggedEnvironmentObjects"] = true,
                ["Persistence.AutoGrabDelay"] = 1.0f,
                
                // Bottomless Bag settings
                ["BottomlessBag.EnableBottomlessBag"] = true,
                ["BottomlessBag.AddedCapacity"] = "INF",
                ["BottomlessBag.EnableStockRefreshClamping"] = true,
                ["BottomlessBag.CycleCooldown"] = 0.2f,
                ["BottomlessBag.EnableMouseWheelScrolling"] = true,
                ["BottomlessBag.InverseMouseWheelScrolling"] = false,
                ["BottomlessBag.AutoPromoteMainSeat"] = true,
                ["BottomlessBag.PrioritizeMainSeat"] = false,
                
                // HUD settings
                ["Hud.EnableCarouselHUD"] = true,
                ["Hud.CarouselSpacing"] = 45.0f,
                ["Hud.CarouselAnimationDuration"] = 0.4f,
                ["Hud.CenterSlotX"] = 25.0f,
                ["Hud.CenterSlotY"] = 50.0f,
                ["Hud.CenterSlotScale"] = 1.0f,
                ["Hud.CenterSlotOpacity"] = 1.0f,
                ["Hud.CenterSlotShowIcon"] = true,
                ["Hud.CenterSlotShowWeightIcon"] = true,
                ["Hud.CenterSlotShowName"] = true,
                ["Hud.CenterSlotShowHealthBar"] = true,
                ["Hud.CenterSlotShowSlotNumber"] = true,
                ["Hud.SideSlotX"] = 20.0f,
                ["Hud.SideSlotY"] = 5.0f,
                ["Hud.SideSlotScale"] = 0.8f,
                ["Hud.SideSlotOpacity"] = 0.3f,
                ["Hud.SideSlotShowIcon"] = true,
                ["Hud.SideSlotShowWeightIcon"] = true,
                ["Hud.SideSlotShowName"] = true,
                ["Hud.SideSlotShowHealthBar"] = true,
                ["Hud.SideSlotShowSlotNumber"] = true,
                ["Hud.EnableDamagePreview"] = true,
                ["Hud.DamagePreviewColor"] = new Color(1f, 0.15f, 0.15f, 0.8f),
                ["Hud.UseNewWeightIcon"] = false,
                ["Hud.WeightDisplayMode"] = WeightDisplayMode.Multiplier,
                ["Hud.ScaleWeightColor"] = true,
                ["Hud.EnableMassCapacityUI"] = true,
                ["Hud.MassCapacityUIPositionX"] = -20.0f,
                ["Hud.MassCapacityUIPositionY"] = 0.0f,
                ["Hud.MassCapacityUIScale"] = 0.8f,
                ["Hud.EnableSeparators"] = true,
                ["Hud.GradientIntensity"] = 1.0f,
                
                // Balance settings
                ["Balance.EnableBalance"] = true,
                ["Balance.BreakoutTimeMultiplier"] = 1.0f,
                ["Balance.MaxSmacks"] = 3,
                ["Balance.AoEDamageDistribution"] = AoEDamageMode.Split,
                ["Balance.SlotScalingFormula"] = "floor(H/100) + floor(L/3)",
                ["Balance.MassCapacityFormula"] = "700*C",
                ["Balance.EliteFlagMultiplier"] = "1",
                ["Balance.BossFlagMultiplier"] = "1",
                ["Balance.ChampionFlagMultiplier"] = "1",
                ["Balance.PlayerFlagMultiplier"] = "1",
                ["Balance.MinionFlagMultiplier"] = "1",
                ["Balance.DroneFlagMultiplier"] = "1",
                ["Balance.MechanicalFlagMultiplier"] = "1",
                ["Balance.VoidFlagMultiplier"] = "1",
                ["Balance.AllFlagMultiplier"] = "H/max(B,1)",
                ["Balance.OverencumbranceMax"] = 100.0f,
                ["Balance.StateCalculationMode"] = StateCalculationMode.All,

                ["Balance.MovespeedPenaltyFormula"] = "clamp((T / M) * 0.5, 0, 0.8)",
                ["Balance.BagScaleCap"] = "1",
                ["Balance.MassCap"] = "INF",
            },
            
            // Custom: Placeholder for user-modified settings
            [PresetType.Custom] = new Dictionary<string, object>(),
        };
    }
}
